# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - echo {{.CLI_ARGS}}
    silent: true

  nest:generate:
    cmds:
      - npx nest generate controller {{.CLI_ARGS}}  --no-spec
      - npx nest generate service {{.CLI_ARGS}}  --no-spec
      - npx nest generate module {{.CLI_ARGS}}  --no-spec
      - npx nest generate class {{.CLI_ARGS}}  --no-spec

  prisma:migrate:
    cmds:
      - npx prisma migrate dev --name init
  
  prisma:generate:
    cmds:
      - npx prisma generate
  
  prisma:studio:
    cmds:
      - npx prisma studio
      - open http://127.0.0.1:5555
  
  prisma:pull:
    cmds:
      - npx prisma db pull
  
  prisma:push:
    cmds:
      - npx prisma db push
  
  prisma:format:
    cmds:
      - npx prisma format
  

