apiVersion: v1
kind: Secret
metadata:
  name: npsg-secret
  namespace: npsg
type: Opaque
data:
  # postgres://myuser:mypassword@127.0.0.1:5432/nest
  DATABASE_URL: cG9zdGdyZXM6Ly9teXVzZXI6bXlwYXNzd29yZEAxMjcuMC4wLjE6NTQzMi9uZXN0Cg==